version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "03:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 25
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.35
    - 14.14.37
    - 14.14.41
    - 15.0.0
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.23
    - 0.20.25
    - 0.20.28
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: interface-datastore
    versions:
    - 3.0.3
    - 3.0.4
    - 3.0.5
  - dependency-name: datastore-core
    versions:
    - 3.0.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: jquery
    versions:
    - 3.5.1
