name: Lint, Test, & Docs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install
      run: npm install
    - name: Lint
      run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install
      run: npm install
    - name: Test
      run: |
        cd ~ && mkdir -p coverage && mkdir -p test-results/mocha
        MOCHA_FILE=test-results/results.xml npm run test:node -- --reporter=mocha-junit-reporter
        npm run test:browser
    - name: Results
        uses: actions/upload-artifact@v1
        with:
          name: Results
          path: test-results
    - name: Coverage
        uses: actions/upload-artifact@v1
        with:
          name: Coverage
          path: coverage
